services:
  keldurben-server:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: keldurben-server
    restart: unless-stopped
    ports:
      - "8765:8765"
    environment:
      - RUST_LOG=info
      - JWT_SECRET=your-production-secret-key-change-this
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/api/auth/me"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: keldurben-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - keldurben-server
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: keldurben-network
